/**
 * Your_Output_File.xlsx auto-fill.
 *
 * Har resident ke "- Input" sheet se 3 din ke progress notes padho, checker chalao,
 * aur matching "- Your Output" sheet ko bharo:
 *     Day | Flag Type | Field | Explanation
 *
 * Run:
 *   npx tsx src/scripts/fill-output.ts
 *   npx tsx src/scripts/fill-output.ts "C:/path/to/Your_Output_File.xlsx"
 *
 * Note: writeFile output sheet ki styling reset kar deta hai (data correct rehta hai).
 */
import "dotenv/config";
import * as path from "path";
import * as XLSX from "xlsx";
import { runChecker } from "../lib/checker";

const DEFAULT_FILE =
  "C:/Users/Krish/Desktop/processx/Interview-AI/Your_Output_File.xlsx";

const FILE = process.argv[2] || DEFAULT_FILE;

type Row = (string | number)[];

/** Input sheet se [dayNumber, noteText] nikaalo. */
function parseInputNotes(rows: Row[]): { day: number; note: string }[] {
  const out: { day: number; note: string }[] = [];
  for (const r of rows) {
    const c0 = String(r[0] ?? "").trim();
    const m = c0.match(/^Day\s*(\d)/i);
    if (m) {
      const note = String(r[3] ?? "").trim();
      if (note) out.push({ day: Number(m[1]), note });
    }
  }
  return out;
}

function flagType(status: "MISSING" | "VAGUE"): string {
  return status === "MISSING" ? "❌ Missing" : "⚠ Vague";
}

async function main() {
  console.log(`Reading: ${FILE}`);
  const wb = XLSX.readFile(FILE);

  const inputSheets = wb.SheetNames.filter((n) => n.endsWith("- Input"));
  if (inputSheets.length === 0) {
    throw new Error("No '- Input' sheets found. Is this the right file?");
  }

  for (const inName of inputSheets) {
    const resident = inName.replace(/\s*-\s*Input$/, "").trim();
    const outName = `${resident} - Your Output`;
    if (!wb.SheetNames.includes(outName)) {
      console.warn(`  ! No output sheet for "${resident}" (expected "${outName}") — skipping`);
      continue;
    }

    const inputRows = XLSX.utils.sheet_to_json<Row>(wb.Sheets[inName], {
      header: 1,
      blankrows: false,
      defval: "",
    });
    const notes = parseInputNotes(inputRows);

    console.log(`\n=== ${resident} (${notes.length} days) ===`);

    // Output sheet ke header rows (title + instruction + column header) preserve karo.
    const aoa: Row[] = [
      [`Your Output — ${resident}`, "", "", ""],
      ["Generated by the Falls Documentation Checker.", "", "", ""],
      ["Day", "Flag Type", "Field", "Explanation"],
    ];

    let totalFlags = 0;
    for (const { day, note } of notes) {
      const result = await runChecker(day, note);
      if (result.compliant) {
        aoa.push([
          `Day ${day}`,
          "✅ Complete",
          "All fields present",
          `Day ${day} note meets all required documentation criteria. No flags raised.`,
        ]);
        console.log(`  Day ${day}: ✅ compliant`);
      } else {
        for (const f of result.flags) {
          aoa.push([`Day ${day}`, flagType(f.status), f.label, f.fixMessage]);
        }
        totalFlags += result.flags.length;
        console.log(`  Day ${day}: ${result.flags.length} flag(s)`);
      }
    }

    // Output sheet ko naye data se replace karo (column widths set).
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws["!cols"] = [{ wch: 8 }, { wch: 14 }, { wch: 38 }, { wch: 80 }];
    wb.Sheets[outName] = ws;
    console.log(`  -> wrote ${totalFlags} flag row(s) to "${outName}"`);
  }

  XLSX.writeFile(wb, FILE);
  console.log(`\n✓ Saved: ${path.resolve(FILE)}`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
